apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      restartPolicy: Always
      containers:
      - name: nodejs
        image: nihatcan17/nodejs:1.0
        ports:
        - containerPort: 5000
        env:
          - name: DB_HOST
            value: postgres-service.default.svc.cluster.local
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: Pp123456789
          - name: DB_NAME
            value: clarustodo
          - name: DB_PORT
            value: "5432"
          - name: SERVER_PORT
            value: "5000"