apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      restartPolicy: Always
      containers:
      - name: nodejs
        image: nihatcan17/nodejs:1.0
        ports:
        - containerPort: 5000
        envFrom:
          - name: nodejs-cf
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password