apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      restartPolicy: Always
      containers:
      - name: react
        image: nihatcan17/react:1.0
        ports:
        - containerPort: 3000
        env:
          - name: REACTURL
            value: postgres-service.default.svc.cluster.local